--- #YAML:1.0
name:               Log-Syslog-Fast
version:            0.53
abstract:           Perl extension for sending syslog messages over TCP, UDP,
author:
    - Adam Thomason <athomason@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Log::Syslog::Constants:  1.01
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
